### PR TITLE
Run pylint

### PR DESCRIPTION
**Pull request by jvlmdr**
Hey, any objections to doing this?

### CODE REVIEW

**Comment by jvlmdr** [comment]
Yeah, I totally agree that duplicating the code in `__init__()` and `reset()` is not as nice as before. I did this to fix the following lint warnings (attribute-defined-outside-init):
```
motmetrics/mot.py:163:8: W0201: Attribute 'dirty_events' defined outside __init__ (attribute-defined-outside-init)
motmetrics/mot.py:304:12: W0201: Attribute 'dirty_events' defined outside __init__ (attribute-defined-outside-init)
motmetrics/mot.py:303:12: W0201: Attribute 'cached_events_df' defined outside __init__ (attribute-defined-outside-init)
```
These warnings occur at the sites where those member variables are accessed. (The linter isn't smart enough to realise that `reset()` is called within `__init__()`.)

I didn't want to disable this warning globally because I think it is good to define the member variables in `__init__()` where possible.

I propose two options:
1. Disable the warning within MOTAccumulator.
2. Instead of duplicating the code from `reset()`, simply set all those variable to None and then call `reset()`.

What do you think?

**Comment by cheind** [comment]
looking good. did you disable the warning? haven't found a reference.

**Comment by jvlmdr** [comment]
I did option 2 (initialize all state variables to None in the constructor) rather than option 1 (disable the warning).
https://github.com/jvlmdr/py-motmetrics/compare/jvlmdr:613e1e7...jvlmdr:c1a7228#diff-8a7fa6c9ecbaabedee2e2dadd0e08b01R109

**Comment by cheind** [comment]
Ah ok, didn't spot that. Then lets merge! Thanks Jack 😀

Jack Valmadre <notifications@github.com> schrieb am Sa., 1. Feb. 2020,
15:44:

**Comment by jvlmdr** [comment]
Excellent! Thanks for taking a look!

**Pull request merged**
