### PR TITLE
docs: Addition of the section for custom dataset

### PR DESCRIPTION
**Pull request by khalidw**
This section titled "For custom dataset" includes a guide on how to calculate MOT metrics for custom dataset.

### CODE REVIEW

**Comment by cheind** [comment]
As requested by #131

**Comment by cheind** [comment]
@khalidw looks fine to me. Looking for somone that actually applies your recipe for confirmation to merge.

**Comment by khalidw** [comment]
@cheind yeah it's fine. I used this code for my Master's thesis back in August 2021. It would be great if someone else can confirm.

**Comment by cheind** [comment]
One remark: would you mind updating the Readme to better reflect when to use the tool you advertise and when this is unnecessary?

**Comment by cheind** [comment]
thanks!

**Pull request merged**
