### PR TITLE
enable usage on your own dataset groundtruth

### PR DESCRIPTION
**Pull request by bmetge**
Hey Cheind,

Thanks a lot for your work on this.

By reading at the comment it seems some people want to compute MOTA, MOTP and so on their own datasets, with their own groundtruth,etc...

That was my need as weel, so I did a small new app in order to enable people to get MOT metrics on their own dataset/grountruth:

`python -m motmetrics.apps.eval_my_dataset --groundtruth <path_to_gt_file> --test <path_to_test_file>`

If you think that can be helpful, feel free to accept the pull requests

### CODE REVIEW

**Comment by cheind** [comment]
Thanks for the PR. Will have a look at it when I return.

**Comment by cheind** [comment]
Hi, what's the application doing in particular? How does this differ from `motmetrics/apps/eval_motchallenge.py`? Is it about a different disk-layout of files? If so, I'd rather request to adapt eval_motchallenge to fit this needs, as otherwise we are duplicating 95% of code. What do you think?

**Comment by bmetge** [comment]
Hi, thanks for your feedback, yes indeed they might be a better solution to do it.

So it seems from the issues talks that some people struggle with the expected files disk layout indeed and that some just want to test it on there own datasets. What would be good to add is maybe something like a small python script:

`python compute_mot.py --groundtruth <path_to_gt_file> --test <path_to_test_file>`

The idea is : I have a dataset with a GT file. I outpout my tracker results in the MOT Challenge format. I compute the motmetrics results for my tracker on my dataset.

If my understanding is correct, the current  disk layout of files makes sense for the mot challenge itself, but less sense if you just simply want the metrics on your own dataset. What do you think ?

**Comment by cheind** [comment]
Yes that might make sense. however, I'd rather propose to add this functionality to the current eval script, so that you can either run MOT challenge or custom datasets. Maybe you could come up with an idea on how to incorporate this via command line arguments?

**Comment by cheind** [comment]
@bmetge are you still planning to work on this?

**Comment by cheind** [comment]
I think we can close this. @bmetge reopen if needed.

**Comment by raozhongyu** [comment]
Hi, thanks for your work, i'd like to konw how can i use it on my own dataset

**Pull request closed without merging**
