### PR TITLE
Add tests and bug fixes for empty sequences

### PR DESCRIPTION
**Pull request by jvlmdr**
Resolves issue https://github.com/cheind/py-motmetrics/issues/49

### CODE REVIEW

**Comment by cheind** [comment]
Hi, thanks for the PR. Would you mind changing the destination branch to develop? There might be already merged PRs that could potentially have an impact on your PR.

**Comment by jvlmdr** [comment]
Sure thing, I will close and re-open from my `develop` branch.

**Comment by cheind** [comment]
thanks, also there seems to be warning for `test_metrics_with_no_events`. See https://travis-ci.org/cheind/py-motmetrics/jobs/612478027

**Comment by jvlmdr** [comment]
Let's continue discussion in the new pull request #58

**Pull request closed without merging**
