### PR TITLE
Add tests and bug fixes for empty sequences

### PR DESCRIPTION
**Pull request by jvlmdr**
Resolves issue #49

### CODE REVIEW

**Comment by jvlmdr** [comment]
Hey! As you noted in the old PR #57 there are 2 warnings arising in `test_metrics_with_no_events`. These are due to the `0 / 0` operations which result in `nan`-valued metrics, arguably the correct output. Would you like me to modify the code such that `nan` is returned without raising an error?

**Comment by cheind** [comment]
Hi, I since empty accumulators are now supported, I think they should not raise warnings of that kind.

**Comment by jvlmdr** [comment]
OK, that makes sense to me. How do you feel about a change like this?
https://github.com/jvlmdr/py-motmetrics/compare/develop...nan_warn

**Comment by cheind** [comment]
puh, didn't expect that change to have so much impact. But yes that's the cleanest solution. We could also go for module-wise disabling of warnings, but I guess that would complicate future bug-finding. So let's stick with that.  I'll be merge this now, but won't be able to release a new version till a couple of weeks (pending conferences). Thanks!

**Comment by jvlmdr** [comment]
Oh sorry, I hadn't actually added those changes to the PR yet. I added another one that includes them. #59

**Pull request merged**
