### PR TITLE
adding suport for reading .mat and .xml format annotations given by UA-DETRAC challenge.

### PR DESCRIPTION
**Pull request by muaz-urwa**
UA-DETRAC is an important multiple object tracking benchmark which focuses on road traffic scenarios. It is now a part of "AI City Challenge". 

Challenge requires you to produce results in "MOT Challenge" format but the ground truth annotations are only available in .XML and .MAT formats which structure very different from MOT format. I had to spend several hours to parse these files and convert them into MOT format so that I can use motmetrics.
 
I have made following additions to support UA-DETRAC benchmark:
- added new formats and relevant file loaders to io.py
- updated the requirements file.
- created a new app specifically for evaluating py-motmetrics for U-DETRAC challenge.

Please review and add if you think it is useful. Let me know if you need any modifications.

Regards

### CODE REVIEW

**Comment by cheind** [comment]
This sounds useful, thank you! Would you mind changing the merging destination to develop branch?

**Comment by muaz-urwa** [comment]
Sure, done.

**Comment by cheind** [comment]
Thanks! Also is there any unit test you could add to `tests\` that would prove correctness of execution for future versions of motmetrics. I.e for MOT16 I added a test case based on a small sample input file (.xml, .mat in your case) with expected results.

**Comment by muaz-urwa** [comment]
Ah sure, I have added similar unit test for detrac data loaders.

**Comment by cheind** [comment]
thanks, merged. will be released with next version.

**Comment by fguney** [comment]
Are there any plans to integrate the aggregated tracking metric used in DETRAC overall detection thresholds, i.e. 0:0.1:1? This way, it is not comparable to official results in the benchmark.

**Comment by cheind** [comment]
linking this to #84

**Comment by goldentimecoolk** [comment]
> 

Hi, have you finished the evaluation under the detrac-format? I'm not sure where to control the detection thresholds. I guess  it should be the confidence threshold in NMS during detection postprocessing. Can you help me? Any other feedback is also welcome. Thank you.

**Pull request merged**
