### PR TITLE
Get ride of np.bool deprecation warning.

### PR DESCRIPTION
**Pull request by alexlitz**
Missed another DeprecationWarning with the last one.

### CODE REVIEW

**Comment by cheind** [comment]
@alexlitz did you see my code comment about public API concern?

**Comment by alexlitz** [comment]
@cheind no, I do not see a comment about that.

**Comment by cheind** [comment]
Here https://github.com/cheind/py-motmetrics/pull/155/files/fc06cd2e66c57250d1322457b59a52232c951ee4

**Comment by facundo-lezama** [comment]
@cheind @alexlitz Please see issue https://github.com/cheind/py-motmetrics/issues/172, I believe merging this PR is pretty urgent.

**Comment by cheind** [comment]
@facundo-lezama thanks for pointing this out!

**Comment by cheind** [comment]
I've found that `bool_` is part of the public API here
https://numpy.org/doc/stable/user/basics.types.html

So I will merge this to develop.

**Pull request merged**
