### PR TITLE
Added Docker Support

### PR DESCRIPTION
**Pull request by christosavg**
Hi! 

I added docker support on your work since I liked it very much! :+1: 
The reason was to avoid messing with system python3, fix the pandas bug and to have the metrics distributed among different systems.

I have updated the ReadMe file too.

If you find this useful feel free to merge! :)
Chris.

### CODE REVIEW

**Comment by cheind** [comment]
Hi Chris, thanks for the PR. Certainly useful. Currently I see two issues

it seems like your commit 908cfbe contains many jpg / txt files. I guess that's an oversight when committing. Could clean the files up. Also seems like you've been adding some auto-saved files that shouldn't be part of the commit.

Secondly it seems like the auto-build is broken:
https://ci.appveyor.com/project/cheind/py-motmetrics/build/1.0.15/job/9etl9dx781lpqeur?fullLog=true
I don't think that's due to your commit though, but rather due to internal changes of pip. I will have a look at this.

**Comment by christosavg** [comment]
Hi Christoph,
Thanks for the feedback. I've cleaned the data files up, they shouldn't be there indeed. 
I'm not familiar with the auto-builds so I can't really tell what's the issue there.

**Comment by cheind** [comment]
Thanks again. I've seen you are basing your merge request on master. I'm using the git-flow model, so PRs are based on the develop branch. Any easy way for you to change this? Also 
 - the `readme.md~` shouldn't be part of the commit, should it?
 - i've seen you've modified readme.md in a way where you have the new docs on top. Is there any place to fit the docker info better within the readme?
 - Also, should I link to your github account for credits?

**Comment by christosavg** [comment]
- Regarding branches, should I issue a new PR on the develop branch?
   It's not quite clear to me since I'm not that familiar with git.
   - I'll remove the ~ file in the next commit and update the ReadMe docker
   section too.
   - Feel free to link to my github account :)


Thanks for pointing out these issues!

**Comment by christosavg** [comment]
Oh nevermind on that branch thing, I figured it out it was a single edit on
the GitHub page.
I'm committing the ReadMe changes and pushing again.

**Comment by cheind** [comment]
Merged to develop, will need to investigate the windows build error.

**Pull request merged**
